// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11kwss_po2w9VIwWlgAqWOLpJp4escVI',
    appId: '1:145757189714:web:c230f1c769aa82c5ca918b',
    messagingSenderId: '145757189714',
    projectId: 'quick-read-14911',
    authDomain: 'quick-read-14911.firebaseapp.com',
    databaseURL: 'https://quick-read-14911-default-rtdb.firebaseio.com',
    storageBucket: 'quick-read-14911.appspot.com',
    measurementId: 'G-4GB341672J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22uaeZE_J3xY8pEIGC8rlcItLEdLMYzU',
    appId: '1:145757189714:android:c46efca1af48bd23ca918b',
    messagingSenderId: '145757189714',
    projectId: 'quick-read-14911',
    databaseURL: 'https://quick-read-14911-default-rtdb.firebaseio.com',
    storageBucket: 'quick-read-14911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQoXF3OFhUc4npfvQGAp_h9R9OPti7XA',
    appId: '1:145757189714:ios:17aa25e7292b9fc5ca918b',
    messagingSenderId: '145757189714',
    projectId: 'quick-read-14911',
    databaseURL: 'https://quick-read-14911-default-rtdb.firebaseio.com',
    storageBucket: 'quick-read-14911.appspot.com',
    iosClientId: '145757189714-7fp8vj1nk0d5hgqp9jak2l2iqfgntop6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickRead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDQoXF3OFhUc4npfvQGAp_h9R9OPti7XA',
    appId: '1:145757189714:ios:33fccf9d350eca5dca918b',
    messagingSenderId: '145757189714',
    projectId: 'quick-read-14911',
    databaseURL: 'https://quick-read-14911-default-rtdb.firebaseio.com',
    storageBucket: 'quick-read-14911.appspot.com',
    iosClientId: '145757189714-90b0o5k3hcl6oi5n01j6sl9q3agnt6be.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickRead.RunnerTests',
  );
}
